Develop
a-grebnev-91-tech/java-explore-with-me pull request #1
Opened 2022-10-31 18:59 UTC by a-grebnev-91-tech

2022-11-01 16:41 UTC, damirovna requested changes

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
[Нужно исправить]

Пожалуйста, ограничьте размеры полей разумными ограничениями, например максимально возможный размер адреса электронной почты можно найти в https://www.rfc-editor.org/rfc/rfc5321#section-4.5.3

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/resources/schema.sql
> +    state              VARCHAR   NOT NULL,
[Можно лучше]

Можно добавить дефолтное значение 'PENDING'

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/java/ru/practicum/dto/compilation/NewCompilationDto.java
> +    private String title;
[Нужно исправить]

Нужно добавить аннотацию @SiZe

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    private Integer participantLimit = 0;
[Нужно исправить]

Нужно добавить аннотацию запрещающую отрицательное количество участников

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    @EventDateInFuture
[Отлично]

Хорошая идея!

2022-11-01 16:41 UTC, damirovna commented on ewm-main-server/src/main/java/ru/practicum/dto/event/UpdateEventRequest.java
> +    private Integer participantLimit;
[Нужно исправить]

Нужно добавить аннотацию запрещающую отрицательное количество участников

2022-11-01 16:41 UTC, damirovna commented on pom.xml
> +    <dependencies>
[Нужно исправить]

 Не нужно указывать связи, так как проект многомодульный, и такой блок в родительском pom’е жёстко задаст список зависимостей для всех дочерних модулей, а в нашем случае (и в большинстве случаев) это не нужно.

2022-11-02 06:40 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
На последнем вебинаре нам наставник говорил, что на проде стараются не накладывать констрейнты на БД, а оставлять их по максимуму на уровне приложения потому, что когда нужно будет их изменить это будет больно. :)
Исправил.

2022-11-02 06:45 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/resources/schema.sql
> +    state              VARCHAR   NOT NULL,
Исправил

2022-11-02 06:50 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/java/ru/practicum/dto/compilation/NewCompilationDto.java
> +    private String title;
В спецификации не указаны требования по этим полям.
Исправил

2022-11-02 06:51 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    private Integer participantLimit = 0;
Исправил

2022-11-02 06:52 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    @EventDateInFuture
Не исправил :)

2022-11-02 06:53 UTC, a-grebnev-91-tech commented on ewm-main-server/src/main/java/ru/practicum/dto/event/UpdateEventRequest.java
> +    private Integer participantLimit;
Исправил

2022-11-02 07:17 UTC, a-grebnev-91-tech commented on pom.xml
> +    <dependencies>
Поправлето.

2022-11-02 15:29 UTC, damirovna commented on ewm-main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Видимо у нас небольшие творческие разногласия с вашим наставником :) Так бывает, работа такая, что иногда нет единого менения по вопросу, но я учту это при проверке дипломов вашей когорты, спасибо за информацию!

2022-11-02 15:30 UTC, damirovna approved these changes
Мои поздравления!

2022-11-02 18:23 UTC, merged